<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <WarningsAsErrors />
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.MariaDb" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PolarSharp.MultiTenant.Identity\PolarSharp.MultiTenant.Identity.csproj" />
    <ProjectReference Include="..\..\src\PolarSharp.MultiTenant.Identity.SqlServer\PolarSharp.MultiTenant.Identity.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\PolarSharp.MultiTenant.Identity.Sqlite\PolarSharp.MultiTenant.Identity.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\PolarSharp.MultiTenant.Identity.PostgreSQL\PolarSharp.MultiTenant.Identity.PostgreSQL.csproj" />
    <ProjectReference Include="..\..\src\PolarSharp.MultiTenant.Identity.MariaDb\PolarSharp.MultiTenant.Identity.MariaDb.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
