namespace PolarSharp.PrepaidWallets.EventStore.EntityFrameworkCore;

/// <summary>
/// EF Core entity mapped to the <c>wallet_events</c> table. Holds one row per event in a wallet's
/// stream — the JSON payload, the type discriminator, the sequence number, and an optional
/// idempotency key.
/// </summary>
/// <remarks>
/// Per Case Study 02 step 1 ("Choose the event-store backend") schema sketch:
/// <code>
/// wallet_events
///   id, wallet_id, sequence_no, event_type, event_payload_json,
///   idempotency_key, occurred_at, actor_user_id, source_ip_hash
/// </code>
/// </remarks>
public sealed class WalletEventRecord
{
    /// <summary>Row primary key — a fresh Guid generated by the application.</summary>
    public Guid Id { get; set; }

    /// <summary>Foreign key into <c>wallet_snapshots.wallet_id</c>.</summary>
    public Guid WalletId { get; set; }

    /// <summary>Position in the wallet's stream. Unique with <see cref="WalletId"/>.</summary>
    public long SequenceNo { get; set; }

    /// <summary>The event-type discriminator (e.g. <c>"wallet.funded"</c>).</summary>
    public string EventType { get; set; } = string.Empty;

    /// <summary>JSON-serialized event body.</summary>
    public string EventPayloadJson { get; set; } = string.Empty;

    /// <summary>The originating command's idempotency key. Unique with <see cref="WalletId"/>.</summary>
    public string IdempotencyKey { get; set; } = string.Empty;

    /// <summary>UTC timestamp the event was recorded.</summary>
    public DateTimeOffset OccurredAt { get; set; }

    /// <summary>The actor that caused the event.</summary>
    public Guid ActorUserId { get; set; }
}
