<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <WarningsAsErrors />
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PolarSharp.EcommerceStorefronts.Abstractions\PolarSharp.EcommerceStorefronts.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\PolarSharp.EcommerceStorefronts\PolarSharp.EcommerceStorefronts.csproj" />
    <ProjectReference Include="..\..\src\PolarSharp.EcommerceStorefronts.Pipelines.OrderProcessing\PolarSharp.EcommerceStorefronts.Pipelines.OrderProcessing.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
